global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@guardagent.io'
  smtp_auth_username: 'alerts@guardagent.io'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'sre@guardagent.io'
    subject: '[CRITICAL] GuardAgent Alert: {{ .GroupLabels.alertname }}'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Severity: {{ .CommonLabels.severity }}
      Instance: {{ .CommonLabels.instance }}
      
      {{ range .Alerts }}
      Description: {{ .Annotations.description }}
      Summary: {{ .Annotations.summary }}
      {{ end }}
  webhook_configs:
  - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    send_resolved: true
    title: 'GuardAgent Critical Alert'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

- name: 'warning-alerts'
  email_configs:
  - to: 'ops@guardagent.io'
    subject: '[WARNING] GuardAgent Alert: {{ .GroupLabels.alertname }}'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Severity: {{ .CommonLabels.severity }}
      Instance: {{ .CommonLabels.instance }}
      
      {{ range .Alerts }}
      Description: {{ .Annotations.description }}
      Summary: {{ .Annotations.summary }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
